<!doctype html>
<html lang="sv">
    <head>
        <meta charset="utf-8">
        <title>Pivøl - Home</title>
        <!-- Bootstrap CDN-->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0/lux/bootstrap.min.css" rel="stylesheet" integrity="sha384-GxhP7S92hzaDyDJqbdpcHqV5cFflxAx0Yze/X7vUONp43KK1E8eUWaJIMkit3D0R" crossorigin="anonymous">

        <!-- Pivol CSS -->
        <link rel="stylesheet" href="css/style.css">
    </head>
    <body class="home">
        <header class="page-header heady text-center">
            <h1>Pivøl</h1>
        </header>
        <?= DS\View::make("widget/navbar")->with(compact("navBars", "page")) ?>

        <div class="jumbotron text-center">
            <div class="container">
                <?= $content ?>
            </div>
        </div>


        <!-- Footer -->
        <footer class="footer bg-dark">
            <div class="container">
              <span class="text-muted">Pivøl &copy; 2018 </span>
            </div>
        </footer>


        <!-- Bootstrap JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!-- AJAX-->
        <script src="js/script.js"></script>
    </body>
</html>
