<nav id="nav" class="navbar navbar-expand-lg navbar-dark bg-dark">
     <a class="navbar-brand" href="#">Pivøl</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
     </button>
         <ul class="navbar-nav mr-auto">
             <?php foreach($navBars as $key => $navbar): ?>
                 <?php if(($navbar['seenBy'] == 'user') && !isset($_SESSION['user'])): ?>
                   <?php continue; ?>
                 <?php elseif(($navbar['seenBy'] == 'none-user') && isset($_SESSION['user'])): ?>
                   <?php continue; ?>
                 <?php else: ?>
                   <li <?= $key == $page ? "class='active nav-item'" : "class='nav-item'" ?>>
                       <a class="nav-link" href='<?= $navbar['href'] ?>'>
                           <?= $key ?>
                       </a>
                   </li>
                 <?php endif;?>
             <?php endforeach; ?>
        </ul>
</nav>
