<div class="row">
  <div class="col-6 col-sm-6 col-md-6 col-lg-6">
      <h1 class="display-4">About Pivl</h1>
      <p class="lead">Pivøl is an app that allows users to search for beer, brands, breweries, and such - to get information about ingredients, volume, alcohol content and similar kinds of beer. </p>
      <hr class="my-4">

      <p class="lead">If you have any questions, or wish to collaborate -  leave us a message, and we will keep in touch as soon as possible.</p>

      <p class="lead">
          <a class="btn btn-dark btn-lg" href="#" role="button">Learn more</a>
      </p>

  </div>
  <div class="col-1 col-sm-1 col-md-1 col-lg-1"></div>
  <div class="col-5 col-sm-5 col-md-5 col-lg-5">
      <h1 class="display-5">Contact us</h1>

      <form class="text-left">
          <fieldset>
              <legend></legend>
              <div class="form-group row">
                  <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
                  <div class="col-sm-10">
                      <input type="text" readonly="" class="form-control-plaintext" id="staticEmail" value="hello@pivl.com">
                  </div>
              </div>
              <div class="form-group">
                  <label for="exampleInputEmail1">Email address</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                  <label for="exampleTextarea">Message</label>
                  <textarea class="form-control" id="exampleTextarea" rows="4"></textarea>
              </div>
              <fieldset class="form-group">
                  <legend>E-mail updates</legend>
                  <div class="form-check">
                      <label class="form-check-label">
                          <input class="form-check-input" type="checkbox" value="" checked="">
                          I would like to recieve updates regarding Pivøl to my email—I am ready to hear great things.
                      </label>
                  </div>
              </fieldset>
              <button type="submit" class="btn btn-dark">Submit</button>
          </fieldset>
      </form>
  </div>


</div>
