<div class="row">
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
<div class="card">
    <div class="card-body results">
        <div class="row align-items-center item">
            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3">
                <img src="<?= (array_key_exists("labels",$results) ? $results['labels']['medium'] : "img/beer-tile.png" ) ?>" alt="beer icon" class="img-thumbnail"> 
            </div>
            <div class="col-4 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <p>IBU: <?= (array_key_exists("ibu",$results) ? $results['ibu'] : "N/A" ) ?></p>
                <!--<p>SRM: <?= (array_key_exists("srm",$results) ? $results['srm'] : "N/A" ) ?></p> -->
                <p>Alcohol Volume: <?= (array_key_exists("abv",$results) ? $results['abv'] : "N/A" ) ?> %</p>
            </div>
            <div class="col-4 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <p>Is Organic: <?= (array_key_exists("isOrganic",$results) ? $results['isOrganic'] : "Not defined" ) ?></p>
                <p>Last Updated: <?= (array_key_exists("updateDate",$results) ? $results['updateDate'] : "Not defined" ) ?></p>
                <p>Status: <?= (array_key_exists("status",$results) ? $results['status'] : "Not defined" ) ?></p>
            </div>
        </div>
        <div class="row align-items-left item">
            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3 text-center">
                <h5><?= (array_key_exists("name",$results) ? $results['name'] : "Not defined" ) ?></h5>
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center ingrediens">
                    <p>Ingrediens: </p>
                </div>
            </div>
            <div class="col-8 col-sm-8 col-md-8 col-lg-8 col-xl-8">
                <p>
                    Saison brewed for the end of a never ending summer. Straight up saison with a hint of coriander
                    <?= (array_key_exists("description",$results) ? $results['description'] : "Not defined" ) ?>
                </p>
            </div>
        </div>
    </div>
</div>



</div>
</div>
