<div class="row">
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
<div class="alert alert-success" role="alert" style="display: none;">
    <p class="statusText">Finished</p>
</div>

<div class="card">
    <div class="card-body results">
        <div class="row align-items-center item">
            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3">
                <img src="img/beer-tile.png" alt="beer icon" class="img-thumbnail">
            </div>
            <div class="col-4 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <p>IBU: N/A</p>
                <p>SRM: N/A</p>
                <p>Alcohol Volume: 5%</p>
            </div>
            <div class="col-4 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <p>Is Organic: No</p>
                <p>Last Updated: 2016-07-16 14:22:07</p>
                <p>Status: N/A</p>
            </div>
        </div>
        <div class="row align-items-left item">
            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3 text-center">
                <h5>E'te' Sans Fin</h5>
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center ingrediens">
                    <p>Ingrediens: </p>
                </div>
            </div>
            <div class="col-8 col-sm-8 col-md-8 col-lg-8 col-xl-8">
                <p>
                    Saison brewed for the end of a never ending summer. Straight up saison with a hint of coriander
                </p>
            </div>
        </div>
    </div>
</div>



</div>
</div>
