<div class="row">
  <div class="col-12 col-sm-12 col-md-12 col-lg-12">

      <h1 class="display-3">Hello, beer lover!</h1>
      <p class="lead">Pivøl is an app that allows users to search for beer, brands, breweries, and such -  to get information about ingredients, volume, alcohol content and similar kinds of beer. </p>
      <hr class="my-4">
      <p class="textP">Search for beer in the field below - and Pivøl will fetch some results for you from the database. </p>
      <form class="form-inline my-2 my-lg-0 mx-auto searchForm" method="POST">
          <input name="search"  id="searchInput" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button name="btn" id="searchBtn" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <br>
      <p class="lead">
          <a class="btn btn-dark btn-lg disabled" href="#" role="button">Learn more</a>
      </p>

      <?php if($results != NULL): ?>

      <?php endif; ?>
  </div>
</div>
