<div class="row">
  <div class="col-12 col-sm-12 col-md-12 col-lg-12">

      <h1 class="display-3">Hello, beer lover!</h1>
      <p class="lead">Pivøl is an app that allows users to search for beer, brands, breweries, and such -  to get information about ingredients, volume, alcohol content and similar kinds of beer. </p>
      <hr class="my-4">
      <p class="textP">Search for beer in the field below - and Pivøl will fetch some results for you from the database. </p>
      <form class="form-inline my-2 my-lg-0 mx-auto searchForm" method="POST">
          <input name="search"  id="searchInput" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button name="btn" id="searchBtn" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <br>
      <p class="lead">
          <a class="btn btn-dark btn-lg disabled" href="#" role="button">Learn more</a>
      </p>

      <?php if(isset($results)): ?>
        <div class="card">
            <div class="card-body results">
            <div class="row">
                <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3 picture">Label</div>
                <div class="col-5 col-sm-5 col-md-5 col-lg-5 col-xl-5 name">Name</div>
                <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3 volume">Alcohol Volume </div>
            </div>


              <?php foreach($results as $key => $value): ?>
                  <?php if($key < sizeof($results)): ?>
                        <div class="row align-items-center item">
                            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3 picture">
                                <?php if(!array_key_exists("labels",$value)): ?>
                                    <img src="img/beer-tile.png" alt="beer icon" class="img-thumbnail">
                                <?php else: ?>
                                    <img src="<?= $value['labels']['medium']?>" alt="beer icon" class="img-thumbnail">
                                <?php endif; ?>
                            </div>
                            <div class="col-5 col-sm-5 col-md-5 col-lg-5 col-xl-5 name">
                                <a class="itemLink" href="home/id/<?= $value['id'] ?>"><?= $value['name'] ?></a>
                            </div>
                            <div class="col-3 col-sm-3 col-md-3 col-lg-3 col-xl-3 volume">
                                <?php if(array_key_exists("abv",$value)): ?>
                                    <p><?= $value['abv']  ?></p>
                                <?php else: ?>
                                    <p>N/A</p>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>

            </div>
        </div>
      <?php endif; ?>
  </div>
</div>
